temp switch to a branch with ncdf output
atmos-cloud-sim-uj/PySDMachine.jl pull request #4
Opened 2020-10-01 22:30 UTC by trontrytel

2020-10-02 14:12 UTC, slayoo requested changes

2020-10-02 14:12 UTC, slayoo commented on .github/workflows/main.yml
> -          git clone --depth 1 https://github.com/CliMA/ClimateMachine.jl.git
Let's do ``git clone --depth 1 --branch aj/KM_ncdf_output``
Just to speed things up - as of now this reduced the amount of data to fetch from 150 MiB to 800 KiB!

2020-10-02 19:16 UTC, trontrytel commented on .github/workflows/main.yml
> -          git clone --depth 1 https://github.com/CliMA/ClimateMachine.jl.git
done

2020-10-02 22:56 UTC, slayoo approved these changes

2020-10-03 00:41 UTC, trontrytel commented
![velo](https://user-images.githubusercontent.com/1196696/94979226-67727980-04d6-11eb-8c66-ed24cc3bf3f0.png)
![water](https://user-images.githubusercontent.com/1196696/94979228-6fcab480-04d6-11eb-8b3f-7e81ecd43c27.png)
![profiles](https://user-images.githubusercontent.com/1196696/94979231-735e3b80-04d6-11eb-8775-8507b7ee0c82.png)

2020-10-16 16:08 UTC, merged